# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Tela_master.ui'
#
# Created: Mon Dec 28 14:13:47 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Projeto_Chaves(object):
    def setupUi(self, Projeto_Chaves):
        Projeto_Chaves.setObjectName(_fromUtf8("Projeto_Chaves"))
        Projeto_Chaves.resize(1151, 800)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon/ufpel.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Projeto_Chaves.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(Projeto_Chaves)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_3 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.nivel1 = QtGui.QFrame(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nivel1.sizePolicy().hasHeightForWidth())
        self.nivel1.setSizePolicy(sizePolicy)
        self.nivel1.setFrameShape(QtGui.QFrame.StyledPanel)
        self.nivel1.setFrameShadow(QtGui.QFrame.Raised)
        self.nivel1.setObjectName(_fromUtf8("nivel1"))
        self.gridLayout_2 = QtGui.QGridLayout(self.nivel1)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_6 = QtGui.QLabel(self.nivel1)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_2.addWidget(self.label_6, 0, 0, 1, 2)
        self.label_4 = QtGui.QLabel(self.nivel1)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Noto Sans [unknown]"))
        font.setPointSize(22)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_2.addWidget(self.label_4, 0, 2, 1, 1)
        spacerItem = QtGui.QSpacerItem(403, 17, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 1, 0, 1, 3)
        self.label_5 = QtGui.QLabel(self.nivel1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMaximumSize(QtCore.QSize(16777211, 90))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_2.addWidget(self.label_5, 2, 0, 1, 1)
        self.lineEdit = QtGui.QLineEdit(self.nivel1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.gridLayout_2.addWidget(self.lineEdit, 2, 1, 1, 2)
        self.tableWidget = QtGui.QTableWidget(self.nivel1)
        self.tableWidget.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tableWidget.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setRowCount(0)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setVisible(False)
        self.gridLayout_2.addWidget(self.tableWidget, 3, 0, 1, 3)
        self.but_entr = QtGui.QPushButton(self.nivel1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.but_entr.sizePolicy().hasHeightForWidth())
        self.but_entr.setSizePolicy(sizePolicy)
        self.but_entr.setObjectName(_fromUtf8("but_entr"))
        self.gridLayout_2.addWidget(self.but_entr, 4, 0, 1, 2)
        self.but_rec = QtGui.QPushButton(self.nivel1)
        self.but_rec.setObjectName(_fromUtf8("but_rec"))
        self.gridLayout_2.addWidget(self.but_rec, 4, 2, 1, 1)
        self.but_sair_2 = QtGui.QPushButton(self.nivel1)
        self.but_sair_2.setObjectName(_fromUtf8("but_sair_2"))
        self.gridLayout_2.addWidget(self.but_sair_2, 5, 0, 1, 3)
        self.gridLayout_3.addWidget(self.nivel1, 0, 1, 2, 2)
        self.login = QtGui.QFrame(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.login.sizePolicy().hasHeightForWidth())
        self.login.setSizePolicy(sizePolicy)
        self.login.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.login.setAutoFillBackground(True)
        self.login.setFrameShape(QtGui.QFrame.Box)
        self.login.setFrameShadow(QtGui.QFrame.Raised)
        self.login.setLineWidth(2)
        self.login.setObjectName(_fromUtf8("login"))
        self.gridLayout = QtGui.QGridLayout(self.login)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_3 = QtGui.QLabel(self.login)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.label = QtGui.QLabel(self.login)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.edit_nome = QtGui.QLineEdit(self.login)
        self.edit_nome.setMinimumSize(QtCore.QSize(0, 30))
        self.edit_nome.setMaximumSize(QtCore.QSize(16777215, 30))
        self.edit_nome.setObjectName(_fromUtf8("edit_nome"))
        self.gridLayout.addWidget(self.edit_nome, 2, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.login)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 3, 0, 1, 1)
        self.edit_senha = QtGui.QLineEdit(self.login)
        self.edit_senha.setMinimumSize(QtCore.QSize(0, 30))
        self.edit_senha.setMaximumSize(QtCore.QSize(16777215, 30))
        self.edit_senha.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhNoAutoUppercase|QtCore.Qt.ImhNoPredictiveText)
        self.edit_senha.setEchoMode(QtGui.QLineEdit.Password)
        self.edit_senha.setObjectName(_fromUtf8("edit_senha"))
        self.gridLayout.addWidget(self.edit_senha, 4, 0, 1, 1)
        self.but_ok = QtGui.QPushButton(self.login)
        self.but_ok.setObjectName(_fromUtf8("but_ok"))
        self.gridLayout.addWidget(self.but_ok, 5, 0, 1, 1)
        self.pushButton = QtGui.QPushButton(self.login)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.gridLayout.addWidget(self.pushButton, 6, 0, 1, 1)
        self.but_sair = QtGui.QPushButton(self.login)
        self.but_sair.setObjectName(_fromUtf8("but_sair"))
        self.gridLayout.addWidget(self.but_sair, 7, 0, 1, 1)
        self.gridLayout_3.addWidget(self.login, 0, 0, 1, 1)
        self.nivel2 = QtGui.QFrame(self.centralwidget)
        self.nivel2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.nivel2.setFrameShadow(QtGui.QFrame.Raised)
        self.nivel2.setObjectName(_fromUtf8("nivel2"))
        self.gridLayout_11 = QtGui.QGridLayout(self.nivel2)
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.label_23 = QtGui.QLabel(self.nivel2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_23.sizePolicy().hasHeightForWidth())
        self.label_23.setSizePolicy(sizePolicy)
        self.label_23.setMaximumSize(QtCore.QSize(16777215, 171))
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.gridLayout_11.addWidget(self.label_23, 0, 0, 2, 1)
        self.label_24 = QtGui.QLabel(self.nivel2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.gridLayout_11.addWidget(self.label_24, 0, 1, 1, 1)
        self.listWidget = QtGui.QListWidget(self.nivel2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget.sizePolicy().hasHeightForWidth())
        self.listWidget.setSizePolicy(sizePolicy)
        self.listWidget.setMaximumSize(QtCore.QSize(16777215, 151))
        self.listWidget.setAutoFillBackground(True)
        self.listWidget.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.listWidget.setViewMode(QtGui.QListView.ListMode)
        self.listWidget.setObjectName(_fromUtf8("listWidget"))
        self.gridLayout_11.addWidget(self.listWidget, 1, 1, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(678, 17, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem1, 2, 0, 1, 2)
        self.toolBox = QtGui.QToolBox(self.nivel2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolBox.sizePolicy().hasHeightForWidth())
        self.toolBox.setSizePolicy(sizePolicy)
        self.toolBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.toolBox.setAutoFillBackground(True)
        self.toolBox.setObjectName(_fromUtf8("toolBox"))
        self.retir = QtGui.QWidget()
        self.retir.setGeometry(QtCore.QRect(0, 0, 667, 174))
        self.retir.setObjectName(_fromUtf8("retir"))
        self.gridLayout_4 = QtGui.QGridLayout(self.retir)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.comboBox = QtGui.QComboBox(self.retir)
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.gridLayout_4.addWidget(self.comboBox, 1, 1, 1, 1)
        self.comboBox_3 = QtGui.QComboBox(self.retir)
        self.comboBox_3.setObjectName(_fromUtf8("comboBox_3"))
        self.gridLayout_4.addWidget(self.comboBox_3, 1, 3, 1, 1)
        self.label_7 = QtGui.QLabel(self.retir)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_4.addWidget(self.label_7, 1, 4, 1, 1)
        self.label_8 = QtGui.QLabel(self.retir)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_4.addWidget(self.label_8, 1, 2, 1, 1)
        self.label_9 = QtGui.QLabel(self.retir)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_4.addWidget(self.label_9, 1, 0, 1, 1)
        self.comboBox_4 = QtGui.QComboBox(self.retir)
        self.comboBox_4.setObjectName(_fromUtf8("comboBox_4"))
        self.gridLayout_4.addWidget(self.comboBox_4, 1, 5, 1, 1)
        self.table_retir = QtGui.QTableWidget(self.retir)
        self.table_retir.setMaximumSize(QtCore.QSize(9999999, 999999))
        self.table_retir.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.table_retir.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.table_retir.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.table_retir.setObjectName(_fromUtf8("table_retir"))
        self.table_retir.setColumnCount(0)
        self.table_retir.setRowCount(0)
        self.table_retir.horizontalHeader().setCascadingSectionResizes(True)
        self.table_retir.horizontalHeader().setDefaultSectionSize(200)
        self.table_retir.horizontalHeader().setStretchLastSection(False)
        self.table_retir.verticalHeader().setVisible(False)
        self.table_retir.verticalHeader().setStretchLastSection(False)
        self.gridLayout_4.addWidget(self.table_retir, 4, 0, 1, 6)
        self.pushButton_4 = QtGui.QPushButton(self.retir)
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.gridLayout_4.addWidget(self.pushButton_4, 3, 5, 1, 1)
        self.comboBox_2 = QtGui.QComboBox(self.retir)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_2.setFont(font)
        self.comboBox_2.setObjectName(_fromUtf8("comboBox_2"))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.gridLayout_4.addWidget(self.comboBox_2, 3, 2, 1, 3)
        self.label_10 = QtGui.QLabel(self.retir)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_4.addWidget(self.label_10, 3, 0, 1, 1)
        self.lineEdit_2 = QtGui.QLineEdit(self.retir)
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.gridLayout_4.addWidget(self.lineEdit_2, 3, 1, 1, 1)
        self.toolBox.addItem(self.retir, icon, _fromUtf8(""))
        self.cad = QtGui.QWidget()
        self.cad.setGeometry(QtCore.QRect(0, 0, 667, 295))
        self.cad.setObjectName(_fromUtf8("cad"))
        self.gridLayout_5 = QtGui.QGridLayout(self.cad)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.tabWidget = QtGui.QTabWidget(self.cad)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(348, 277))
        self.tabWidget.setMaximumSize(QtCore.QSize(9999999, 9999999))
        self.tabWidget.setSizeIncrement(QtCore.QSize(0, 0))
        self.tabWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWidget.setAutoFillBackground(True)
        self.tabWidget.setTabPosition(QtGui.QTabWidget.West)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab.sizePolicy().hasHeightForWidth())
        self.tab.setSizePolicy(sizePolicy)
        self.tab.setMaximumSize(QtCore.QSize(9999999, 9999999))
        self.tab.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tab.setAutoFillBackground(True)
        self.tab.setObjectName(_fromUtf8("tab"))
        self.gridLayout_6 = QtGui.QGridLayout(self.tab)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.label_11 = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_6.addWidget(self.label_11, 0, 0, 1, 1)
        self.filtra_nome = QtGui.QLineEdit(self.tab)
        self.filtra_nome.setObjectName(_fromUtf8("filtra_nome"))
        self.gridLayout_6.addWidget(self.filtra_nome, 0, 1, 1, 1)
        self.but_novouser = QtGui.QPushButton(self.tab)
        self.but_novouser.setObjectName(_fromUtf8("but_novouser"))
        self.gridLayout_6.addWidget(self.but_novouser, 0, 2, 1, 1)
        self.but_excluser = QtGui.QPushButton(self.tab)
        self.but_excluser.setObjectName(_fromUtf8("but_excluser"))
        self.gridLayout_6.addWidget(self.but_excluser, 0, 3, 1, 1)
        self.table_user = QtGui.QTableWidget(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.table_user.sizePolicy().hasHeightForWidth())
        self.table_user.setSizePolicy(sizePolicy)
        self.table_user.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.table_user.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.table_user.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.table_user.setObjectName(_fromUtf8("table_user"))
        self.table_user.setColumnCount(0)
        self.table_user.setRowCount(0)
        self.table_user.horizontalHeader().setStretchLastSection(True)
        self.table_user.verticalHeader().setVisible(False)
        self.gridLayout_6.addWidget(self.table_user, 1, 0, 1, 4)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_2.sizePolicy().hasHeightForWidth())
        self.tab_2.setSizePolicy(sizePolicy)
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.gridLayout_7 = QtGui.QGridLayout(self.tab_2)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.label_12 = QtGui.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_7.addWidget(self.label_12, 0, 0, 1, 1)
        self.comboBox_5 = QtGui.QComboBox(self.tab_2)
        self.comboBox_5.setObjectName(_fromUtf8("comboBox_5"))
        self.gridLayout_7.addWidget(self.comboBox_5, 0, 1, 1, 1)
        self.label_13 = QtGui.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_7.addWidget(self.label_13, 0, 2, 1, 1)
        self.comboBox_6 = QtGui.QComboBox(self.tab_2)
        self.comboBox_6.setObjectName(_fromUtf8("comboBox_6"))
        self.gridLayout_7.addWidget(self.comboBox_6, 0, 3, 1, 1)
        self.line_3 = QtGui.QFrame(self.tab_2)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(63, 63, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(63, 63, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(63, 63, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.line_3.setPalette(palette)
        self.line_3.setLineWidth(5)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.gridLayout_7.addWidget(self.line_3, 1, 0, 1, 4)
        self.label_14 = QtGui.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_7.addWidget(self.label_14, 2, 0, 1, 1)
        self.filtra_user = QtGui.QLineEdit(self.tab_2)
        self.filtra_user.setObjectName(_fromUtf8("filtra_user"))
        self.gridLayout_7.addWidget(self.filtra_user, 2, 1, 1, 1)
        self.label_15 = QtGui.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_7.addWidget(self.label_15, 2, 2, 1, 1)
        self.filtra_auto = QtGui.QLineEdit(self.tab_2)
        self.filtra_auto.setObjectName(_fromUtf8("filtra_auto"))
        self.gridLayout_7.addWidget(self.filtra_auto, 2, 3, 1, 1)
        self.listWidget_2 = QtGui.QListWidget(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget_2.sizePolicy().hasHeightForWidth())
        self.listWidget_2.setSizePolicy(sizePolicy)
        self.listWidget_2.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.listWidget_2.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.listWidget_2.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.listWidget_2.setObjectName(_fromUtf8("listWidget_2"))
        self.gridLayout_7.addWidget(self.listWidget_2, 3, 0, 1, 2)
        self.table_autos = QtGui.QTableWidget(self.tab_2)
        self.table_autos.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.table_autos.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.table_autos.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.table_autos.setObjectName(_fromUtf8("table_autos"))
        self.table_autos.setColumnCount(0)
        self.table_autos.setRowCount(0)
        self.table_autos.verticalHeader().setVisible(False)
        self.gridLayout_7.addWidget(self.table_autos, 3, 2, 1, 2)
        self.but_addaut = QtGui.QPushButton(self.tab_2)
        self.but_addaut.setObjectName(_fromUtf8("but_addaut"))
        self.gridLayout_7.addWidget(self.but_addaut, 4, 0, 1, 2)
        self.but_excaut = QtGui.QPushButton(self.tab_2)
        self.but_excaut.setObjectName(_fromUtf8("but_excaut"))
        self.gridLayout_7.addWidget(self.but_excaut, 4, 2, 1, 2)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.gridLayout_8 = QtGui.QGridLayout(self.tab_3)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.pushButton_8 = QtGui.QPushButton(self.tab_3)
        self.pushButton_8.setObjectName(_fromUtf8("pushButton_8"))
        self.gridLayout_8.addWidget(self.pushButton_8, 2, 9, 1, 1)
        self.label_16 = QtGui.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_8.addWidget(self.label_16, 2, 1, 1, 2)
        self.listWidget_3 = QtGui.QListWidget(self.tab_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget_3.sizePolicy().hasHeightForWidth())
        self.listWidget_3.setSizePolicy(sizePolicy)
        self.listWidget_3.setMinimumSize(QtCore.QSize(1, 0))
        self.listWidget_3.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.listWidget_3.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.listWidget_3.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.listWidget_3.setObjectName(_fromUtf8("listWidget_3"))
        self.gridLayout_8.addWidget(self.listWidget_3, 6, 6, 1, 4)
        self.comboBox_7 = QtGui.QComboBox(self.tab_3)
        self.comboBox_7.setObjectName(_fromUtf8("comboBox_7"))
        self.gridLayout_8.addWidget(self.comboBox_7, 0, 3, 1, 7)
        self.label_17 = QtGui.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_8.addWidget(self.label_17, 0, 1, 1, 2)
        self.table_sala = QtGui.QTableWidget(self.tab_3)
        self.table_sala.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.table_sala.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.table_sala.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.table_sala.setObjectName(_fromUtf8("table_sala"))
        self.table_sala.setColumnCount(0)
        self.table_sala.setRowCount(0)
        self.table_sala.horizontalHeader().setStretchLastSection(True)
        self.table_sala.verticalHeader().setVisible(False)
        self.gridLayout_8.addWidget(self.table_sala, 6, 1, 1, 5)
        self.but_excsala = QtGui.QPushButton(self.tab_3)
        self.but_excsala.setObjectName(_fromUtf8("but_excsala"))
        self.gridLayout_8.addWidget(self.but_excsala, 7, 1, 1, 5)
        self.pushButton_11 = QtGui.QPushButton(self.tab_3)
        self.pushButton_11.setMinimumSize(QtCore.QSize(1, 0))
        self.pushButton_11.setObjectName(_fromUtf8("pushButton_11"))
        self.gridLayout_8.addWidget(self.pushButton_11, 7, 6, 1, 2)
        self.pushButton_10 = QtGui.QPushButton(self.tab_3)
        self.pushButton_10.setMinimumSize(QtCore.QSize(3, 0))
        self.pushButton_10.setObjectName(_fromUtf8("pushButton_10"))
        self.gridLayout_8.addWidget(self.pushButton_10, 7, 8, 1, 2)
        self.label_18 = QtGui.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout_8.addWidget(self.label_18, 5, 1, 1, 2)
        self.filtra_sala = QtGui.QLineEdit(self.tab_3)
        self.filtra_sala.setObjectName(_fromUtf8("filtra_sala"))
        self.gridLayout_8.addWidget(self.filtra_sala, 4, 3, 2, 7)
        self.label_19 = QtGui.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout_8.addWidget(self.label_19, 2, 5, 1, 1)
        self.comboBox_8 = QtGui.QComboBox(self.tab_3)
        self.comboBox_8.setObjectName(_fromUtf8("comboBox_8"))
        self.comboBox_8.addItem(_fromUtf8(""))
        self.comboBox_8.addItem(_fromUtf8(""))
        self.comboBox_8.addItem(_fromUtf8(""))
        self.gridLayout_8.addWidget(self.comboBox_8, 2, 6, 1, 3)
        self.line_sala = QtGui.QLineEdit(self.tab_3)
        self.line_sala.setObjectName(_fromUtf8("line_sala"))
        self.gridLayout_8.addWidget(self.line_sala, 2, 3, 1, 2)
        self.line = QtGui.QFrame(self.tab_3)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(63, 63, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(63, 63, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(63, 63, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.line.setPalette(palette)
        self.line.setLineWidth(5)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout_8.addWidget(self.line, 3, 1, 1, 9)
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.gridLayout_9 = QtGui.QGridLayout(self.tab_4)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.lineEdit_8 = QtGui.QLineEdit(self.tab_4)
        self.lineEdit_8.setObjectName(_fromUtf8("lineEdit_8"))
        self.gridLayout_9.addWidget(self.lineEdit_8, 3, 1, 1, 3)
        self.nome_predio = QtGui.QLineEdit(self.tab_4)
        self.nome_predio.setObjectName(_fromUtf8("nome_predio"))
        self.gridLayout_9.addWidget(self.nome_predio, 0, 1, 1, 2)
        self.label_20 = QtGui.QLabel(self.tab_4)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout_9.addWidget(self.label_20, 0, 0, 1, 1)
        self.pushButton_12 = QtGui.QPushButton(self.tab_4)
        self.pushButton_12.setObjectName(_fromUtf8("pushButton_12"))
        self.gridLayout_9.addWidget(self.pushButton_12, 5, 0, 1, 4)
        self.but_addpredio = QtGui.QPushButton(self.tab_4)
        self.but_addpredio.setObjectName(_fromUtf8("but_addpredio"))
        self.gridLayout_9.addWidget(self.but_addpredio, 0, 3, 1, 1)
        self.label_21 = QtGui.QLabel(self.tab_4)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.gridLayout_9.addWidget(self.label_21, 3, 0, 1, 1)
        self.table_predio = QtGui.QTableWidget(self.tab_4)
        self.table_predio.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.table_predio.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.table_predio.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.table_predio.setObjectName(_fromUtf8("table_predio"))
        self.table_predio.setColumnCount(0)
        self.table_predio.setRowCount(0)
        self.table_predio.horizontalHeader().setStretchLastSection(True)
        self.table_predio.verticalHeader().setVisible(False)
        self.gridLayout_9.addWidget(self.table_predio, 4, 0, 1, 4)
        self.line_2 = QtGui.QFrame(self.tab_4)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(63, 63, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(63, 63, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(63, 63, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.line_2.setPalette(palette)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setLineWidth(5)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.gridLayout_9.addWidget(self.line_2, 1, 0, 1, 4)
        self.tabWidget.addTab(self.tab_4, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.gridLayout_10 = QtGui.QGridLayout(self.tab_5)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.label_22 = QtGui.QLabel(self.tab_5)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.gridLayout_10.addWidget(self.label_22, 0, 0, 1, 1)
        self.filtro_login = QtGui.QLineEdit(self.tab_5)
        self.filtro_login.setObjectName(_fromUtf8("filtro_login"))
        self.gridLayout_10.addWidget(self.filtro_login, 0, 1, 1, 1)
        self.but_addlogin = QtGui.QPushButton(self.tab_5)
        self.but_addlogin.setObjectName(_fromUtf8("but_addlogin"))
        self.gridLayout_10.addWidget(self.but_addlogin, 0, 2, 1, 1)
        self.pushButton_14 = QtGui.QPushButton(self.tab_5)
        self.pushButton_14.setObjectName(_fromUtf8("pushButton_14"))
        self.gridLayout_10.addWidget(self.pushButton_14, 0, 3, 1, 1)
        self.table_login = QtGui.QTableWidget(self.tab_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.table_login.sizePolicy().hasHeightForWidth())
        self.table_login.setSizePolicy(sizePolicy)
        self.table_login.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.table_login.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.table_login.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.table_login.setObjectName(_fromUtf8("table_login"))
        self.table_login.setColumnCount(0)
        self.table_login.setRowCount(0)
        self.table_login.horizontalHeader().setStretchLastSection(True)
        self.table_login.verticalHeader().setVisible(False)
        self.gridLayout_10.addWidget(self.table_login, 1, 0, 1, 4)
        self.tabWidget.addTab(self.tab_5, _fromUtf8(""))
        self.gridLayout_5.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.toolBox.addItem(self.cad, icon, _fromUtf8(""))
        self.gridLayout_11.addWidget(self.toolBox, 3, 0, 1, 2)
        self.but_sair_nivel2 = QtGui.QPushButton(self.nivel2)
        self.but_sair_nivel2.setObjectName(_fromUtf8("but_sair_nivel2"))
        self.gridLayout_11.addWidget(self.but_sair_nivel2, 4, 0, 1, 2)
        self.gridLayout_3.addWidget(self.nivel2, 1, 0, 1, 1)
        Projeto_Chaves.setCentralWidget(self.centralwidget)

        self.retranslateUi(Projeto_Chaves)
        self.toolBox.setCurrentIndex(1)
        self.tabWidget.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(Projeto_Chaves)

    def retranslateUi(self, Projeto_Chaves):
        Projeto_Chaves.setWindowTitle(_translate("Projeto_Chaves", "Projeto Chaves Ceng", None))
        self.label_6.setText(_translate("Projeto_Chaves", "<html><head/><body><p><img src=\":/logo/logo_ufpel.png\"/></p></body></html>", None))
        self.label_4.setText(_translate("Projeto_Chaves", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; vertical-align:sub;\">Projeto </span></p><p align=\"center\"><span style=\" font-size:12pt; vertical-align:sub;\">Chaves </span></p><p align=\"center\"><span style=\" font-size:12pt; vertical-align:sub;\">Ceng</span></p></body></html>", None))
        self.label_5.setText(_translate("Projeto_Chaves", "Filtro:", None))
        self.but_entr.setText(_translate("Projeto_Chaves", "Entregar chave", None))
        self.but_rec.setText(_translate("Projeto_Chaves", "Receber chave", None))
        self.but_sair_2.setText(_translate("Projeto_Chaves", "Sair", None))
        self.label_3.setText(_translate("Projeto_Chaves", "<html><head/><body><p><img src=\":/logo/logo_ufpel.png\"/></p></body></html>", None))
        self.label.setText(_translate("Projeto_Chaves", "Login:", None))
        self.label_2.setText(_translate("Projeto_Chaves", "Senha:", None))
        self.but_ok.setText(_translate("Projeto_Chaves", "Entrar", None))
        self.pushButton.setText(_translate("Projeto_Chaves", "Configurações", None))
        self.but_sair.setText(_translate("Projeto_Chaves", "Sair", None))
        self.label_23.setText(_translate("Projeto_Chaves", "<html><head/><body><p align=\"justify\"><img src=\":/logo/logo_ufpel.png\"/><span style=\" font-weight:600; font-style:italic;\">Projeto Chaves Ceng</span></p></body></html>", None))
        self.label_24.setText(_translate("Projeto_Chaves", "Logins ativos:", None))
        self.label_7.setText(_translate("Projeto_Chaves", "Ano:", None))
        self.label_8.setText(_translate("Projeto_Chaves", "Mes:", None))
        self.label_9.setText(_translate("Projeto_Chaves", "Prédio:", None))
        self.pushButton_4.setText(_translate("Projeto_Chaves", "Excluir", None))
        self.comboBox_2.setItemText(0, _translate("Projeto_Chaves", "Todas", None))
        self.comboBox_2.setItemText(1, _translate("Projeto_Chaves", "Em aberto", None))
        self.comboBox_2.setItemText(2, _translate("Projeto_Chaves", "Encerradas", None))
        self.label_10.setText(_translate("Projeto_Chaves", "Filtrar:", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.retir), _translate("Projeto_Chaves", "Retiradas", None))
        self.label_11.setText(_translate("Projeto_Chaves", "Filtrar Nome:", None))
        self.but_novouser.setText(_translate("Projeto_Chaves", "Novo", None))
        self.but_excluser.setText(_translate("Projeto_Chaves", "Excluir", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Projeto_Chaves", "Usuários", None))
        self.label_12.setText(_translate("Projeto_Chaves", "Prédio:", None))
        self.label_13.setText(_translate("Projeto_Chaves", "Sala:", None))
        self.label_14.setText(_translate("Projeto_Chaves", "Usuários:", None))
        self.label_15.setText(_translate("Projeto_Chaves", "Autorizações:", None))
        self.but_addaut.setText(_translate("Projeto_Chaves", "Adicionar", None))
        self.but_excaut.setText(_translate("Projeto_Chaves", "Excluir", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Projeto_Chaves", "Autorizações", None))
        self.pushButton_8.setText(_translate("Projeto_Chaves", "Add. Sala", None))
        self.label_16.setText(_translate("Projeto_Chaves", "Sala:", None))
        self.label_17.setText(_translate("Projeto_Chaves", "Prédio:", None))
        self.but_excsala.setText(_translate("Projeto_Chaves", "Excluir Sala", None))
        self.pushButton_11.setText(_translate("Projeto_Chaves", "Add. Cópia", None))
        self.pushButton_10.setText(_translate("Projeto_Chaves", "Excluir Cópia", None))
        self.label_18.setText(_translate("Projeto_Chaves", "Filtra Sala:", None))
        self.label_19.setText(_translate("Projeto_Chaves", "Direito:", None))
        self.comboBox_8.setItemText(0, _translate("Projeto_Chaves", "Nenhum", None))
        self.comboBox_8.setItemText(1, _translate("Projeto_Chaves", "Todos Prof.", None))
        self.comboBox_8.setItemText(2, _translate("Projeto_Chaves", "Todos Alunos", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Projeto_Chaves", "Salas", None))
        self.label_20.setText(_translate("Projeto_Chaves", "Nome:", None))
        self.pushButton_12.setText(_translate("Projeto_Chaves", "Excluir", None))
        self.but_addpredio.setText(_translate("Projeto_Chaves", "Add. Prédio", None))
        self.label_21.setText(_translate("Projeto_Chaves", "Filtro:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("Projeto_Chaves", "Prédios", None))
        self.label_22.setText(_translate("Projeto_Chaves", "Filtrar Nome:", None))
        self.but_addlogin.setText(_translate("Projeto_Chaves", "Novo", None))
        self.pushButton_14.setText(_translate("Projeto_Chaves", "Excluir", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("Projeto_Chaves", "Logins", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.cad), _translate("Projeto_Chaves", "Cadastros", None))
        self.but_sair_nivel2.setText(_translate("Projeto_Chaves", "Sair", None))

import logo_rc
